ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
    GROUP_BY_SCENE: True
    CYCLE: False
PHYSICS_SIMULATOR:
  TYPE: "Sim-Phys"
  ACTION_SPACE_CONFIG: v0
  GRASP_IMPULSE: 1000.0
  HOLD_THRESH: 0.09
  AC_FREQ_RATIO: 4
  AGENTS: ['AGENT_0']
  DEFAULT_AGENT_ID: 0
  AGENT_0:
    ANGULAR_ACCELERATION: 12.56
    ANGULAR_FRICTION: 1.0
    COEFFICIENT_OF_RESTITUTION: 0.0
    HEIGHT: 0.15
    IS_SET_START_STATE: False
    LINEAR_ACCELERATION: 20.0
    LINEAR_FRICTION: 0.5
    MASS: 32.0
    RADIUS: 0.14
    SENSORS: ['HEAD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'ARM_RGB_SENSOR']
    START_POSITION: [0, 0, 0]
    START_ROTATION: [0, 0, 0, 1]
  HEAD_RGB_SENSOR:
      WIDTH: 848
      HEIGHT: 480
      HFOV: 69
  HEAD_DEPTH_SENSOR:
      WIDTH: 848
      HEIGHT: 480
      #MIN_DEPTH: 0.0
      #MAX_DEPTH: 10.0
      NORMALIZE_DEPTH: False
      HFOV: 69
  ARM_RGB_SENSOR:
      HEIGHT: 480
      WIDTH: 848
      HFOV: 120
  ARM_REST: [0.6, 0.0, 0.9]
  CTRL_FREQ: 120.0
  DEFAULT_AGENT_ID: 0
  FORWARD_STEP_SIZE: 0.25
  HABITAT_SIM_V0:
    ALLOW_SLIDING: True
    ENABLE_PHYSICS: True
    GPU_DEVICE_ID: 0
    GPU_GPU: False
    PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
  LAG_OBSERVATIONS: 1
  ROBOT_URDF: ./data/robots/ep_description/urdf/ep_description.urdf
  SCENE: ./data/replica_cad/stages/scene1.glb
  SEED: 100
  SEMANTIC_SENSOR:
    HEIGHT: 480
    HFOV: 90
    ORIENTATION: [0.0, 0.0, 0.0]
    POSITION: [0, 0.5, 0]
    TYPE: HabitatSimSemanticSensor
    WIDTH: 640
  TILT_ANGLE: 15
  TURN_ANGLE: 10
  TYPE: RearrangeSim-v0
  ep_info: [{
    'episode_id': '1536',
    'scene_id': 'data/replica_cad/stages/scene1',
    'start_position': [0, 0],
    'start_rotation': 180,
    'info': None,
    '_shortest_path_cache': None,
    'art_objs': [],
    'static_objs': [
        ['data/objects/cube_num_1', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [1.0, 0.05, 3.4, 1.0]
        ], 2]],
        ['data/objects/cube_num_1', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [1.0, 0.10, 3.4, 1.0]
        ], 2]],
        ['data/objects/cube_num_2', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [1.9, 0.05, 3.1, 1.0]
        ], 2]],
        ['data/objects/cube_num_2', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [1.9, 0.1, 3.1, 1.0]
        ], 2]],
        ['data/objects/cube_num_3', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [1.5, 0.05, 1.0, 1.0]
        ], 2]],
        ['data/objects/cube_num_3', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [1.5, 0.1, 1.0, 1.0]
        ], 2]],
        ['data/objects/cube_num_4', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [4.0, 0.05, 1.8, 1.0]
        ], 2]],
        ['data/objects/cube_num_4', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [4.0, 0.1, 1.8, 1.0]
        ], 2]],
        ['data/objects/cube_num_5', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [5.1, 0.05, 0.3, 1.0]
        ], 2]],
        ['data/objects/cube_num_5', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [5.1, 0.1, 0.3, 1.0]
        ], 2]],

        ['data/objects/letter_on_box_B', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [2.32, 0.07, 1.89, 1.0]
        ], 1]],
        ['data/objects/letter_on_box_O', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [2.45, 0.07, 1.89, 1.0]
        ], 1]],
        ['data/objects/letter_on_box_X', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [2.58, 0.07, 1.89, 1.0]
        ], 1]],
        ['data/objects/gate_number_1', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [2.22, 0.53, 1.79, 1.0]
        ], 1]],
        ['data/objects/gate_number_2', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [2.45, 0.53, 1.79, 1.0]
        ], 1]],
        ['data/objects/gate_number_3', [[
          [1, 0, 0, 0.0],
          [0, 1, 0, 0.0],
          [0, 0, 1, 0.0],
          [2.68, 0.53, 1.79, 1.0]
        ], 1]],
    ],
    'targets': [
        [0, [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.20000000298023224, -2.0, 0.0, 1.0]]]
    ],
    'fixed_base': True,
    'art_states': [],
    'nav_mesh_path': None,
    'scene_config_path': './orp/scenes/counter_L_analysis.yaml',
    'allowed_region': [],
    'markers': [
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_7', 'relative': [0, 7]},
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_6', 'relative': [0, 6]},
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_5', 'relative': [0, 5]},
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_4', 'relative': [0, 4]},
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_3', 'relative': [0, 3]},
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_2', 'relative': [0, 2]},
        {'local': [0.3, 0.0, 0], 'name': 'cab_push_point_1', 'relative': [0, 1]},
        {'local': [0.1, -0.62, 0.2], 'name': 'fridge_push_point', 'relative': [1, 2]}
    ],
    'force_spawn_pos': None
}]

TASK:
  TYPE: Nav-Phys
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: test
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz

VIDEO_OPTION: ["disk"]
VIDEO_DIR: "videos/test_habitat_evaluator_with_physics/"
